### PR TITLE
close producer during cleanup

### LINKED ISSUE #136: [BUG] - Pulsar Producer leak
**Describe the bug**
When using the connector for a single topic, a customer is seeing the number of connections to the broker increasing dramatically. After reviewing the heap dump, we have determined that the root cause is an excessive number of producer objects are getting created that are never closed.

**Expected behavior**
Only a single producer for a topic should be created and re-used.

**Additional context**
The issue was discussed on [Slack](https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1687994695746099), with the conclusion being that there is an error in the PulsarWriteTask.scala [code](https://github.com/streamnative/pulsar-spark/blob/master/src/main/scala/org/apache/spark/sql/pulsar/PulsarWriteTask.scala#L137) that creates a new producer for each task instead of placing it in the cache and reusing it on subsequent calls.

### PR DESCRIPTION
**Pull request by nlu90**
### Motivation

fix #136 

Currently, producers will stay connected with a broker after each micro-batch, thus causing a broker-side producer spam issue and eventually affecting the broker's performance.

### Modifications

call `producer.close()` when clean up

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

- [ ] This change is a trivial rework / code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:

- [ ] This change added tests and can be verified as follows:

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required`
- [x] `no-need-doc`
- [ ] `doc`

### CODE REVIEW

File: src/main/scala/org/apache/spark/sql/pulsar/PulsarWriteTask.scala [hunk 1]
```diff
@@ -209,6 +209,11 @@ private[pulsar] abstract class PulsarRowWriter(
 
   protected def producerClose(): Unit = {
     producerFlush()
+    if (singleProducer != null) {
+      singleProducer.close()
+    } else {
+      topic2Producer.foreach(_._2.close())
```
Comment (chaoqin-li1123) [inline src/main/scala/org/apache/spark/sql/pulsar/PulsarWriteTask.scala:215]: Do we need to handle exception here?

**Review by sijie — APPROVED** [review]

File: src/main/scala/org/apache/spark/sql/pulsar/PulsarWriteTask.scala (hunk 1 above)
Comment (nlu90) [reply src/main/scala/org/apache/spark/sql/pulsar/PulsarWriteTask.scala:215]: If the exception happens, we will let it propagate. 

And it will be catched here: https://github.com/streamnative/pulsar-spark/blob/master/src/main/scala/org/apache/spark/sql/pulsar/PulsarSinks.scala#L153

**Review by chaoqin-li1123 — APPROVED** [review]
LGTM, thanks!
